# Gemfile
source 'https://rubygems.org'

# Use the latest cocoapods gem
gem 'cocoapods', '1.13.0'

gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'

group :test do
  gem 'rspec-expectations', '2.11.2'
end
