platformVersion = '14.0'

platform :ios, platformVersion

ENV['TRIKOT_FRAMEWORK_NAME']='TRIKOT_FRAMEWORK_NAME'

system("../../../gradlew -p ../../../trikot-viewmodels-declarative/sample/common :trikot-viewmodels-declarative:sample:common:syncFramework -Pkotlin.native.cocoapods.platform=iphonesimulator -Pkotlin.native.cocoapods.archs=arm64 -Pkotlin.native.cocoapods.configuration=Debug")

target 'Sample' do
  use_frameworks!

  pod 'TRIKOT_FRAMEWORK_NAME', :path => '../common'
  pod 'Trikot/viewmodels.declarative', :path => '../../..'
  pod 'Trikot/viewmodels.declarative.UIKit', :path => '../../..'
  pod 'Trikot/viewmodels.declarative.SwiftUI', :path => '../../..'
  pod 'Trikot/streams', :path => '../../..', :inhibit_warnings => true
  pod 'Trikot/http', :path => '../../..', :inhibit_warnings => true
  pod 'Trikot/kword', :path => '../../..', :inhibit_warnings => true
  pod 'SwiftLint'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = platformVersion
      end
    end
  end
end
