platform :ios, '11.3'

install! 'cocoapods', :disable_input_output_paths => true

ENV['TRIKOT_FRAMEWORK_NAME']='MetaviewsSample' 

target 'iosApp' do
  use_frameworks!
  pod 'SwiftLint'
  pod 'MetaviewsSample', :path => '../common'
  pod 'Trikot.metaviews', :git => 'git@github.com:mirego/trikot.metaviews.git', :tag => '0.35.1', :inhibit_warnings => true
  pod 'Trikot.streams', :git => 'git@github.com:mirego/trikot.streams.git', :inhibit_warnings => true
    
  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
