# Gemfile
source 'https://rubygems.org'

# Use the latest cocoapods gem
gem 'cocoapods', '1.13.0'
gem 'cocoapods-generate'
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'
gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)

group :test do
  gem 'rspec-expectations', '2.11.2'
end
