# Gemfile
source 'https://rubygems.org'

# Use the latest cocoapods gem
gem 'cocoapods', '~>1.11.3'
gem 'cocoapods-generate'
gem 'activesupport'
gem "fastlane"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)

group :test do
  gem 'rspec-expectations', '2.11.2'
end
