platformVersion = '11.3'
platform :ios, platformVersion

install! 'cocoapods', :disable_input_output_paths => true

ENV['TRIKOT_FRAMEWORK_NAME']='TRIKOT_FRAMEWORK_NAME'

system("../../../gradlew -p ../../../trikot-viewmodels/sample/common :trikot-viewmodels:sample:common:syncFramework -Pkotlin.native.cocoapods.platform=iphonesimulator -Pkotlin.native.cocoapods.archs=arm64 -Pkotlin.native.cocoapods.configuration=Debug")


target 'iosApp' do
  use_frameworks!
  pod 'SwiftLint'
  pod 'TRIKOT_FRAMEWORK_NAME', :path => '../common'
  pod 'Trikot/viewmodels', :path => '../../..'
  pod 'Trikot/streams', :path => '../../..', :inhibit_warnings => true
    
  target 'iosAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = platformVersion
      end
  end
end
