object Project {
    const val TRIKOT_FOUNDATION = ":trikot-foundation:trikotFoundation"
    const val TRIKOT_STREAMS = ":trikot-streams:streams"
    const val TRIKOT_STREAMS_TEST_UTILS = ":trikot-streams:test-utils"
    const val TRIKOT_HTTP = ":trikot-http:http"
    const val TRIKOT_KWORD = ":trikot-kword:kword"
    const val TRIKOT_KWORD_STREAMS = ":trikot-kword:kword-streams"
    const val TRIKOT_KWORD_FLOW = ":trikot-kword:kword-flow"
    const val TRIKOT_KWORD_SAMPLE_COMMON = ":trikot-kword:sample:common"
    const val TRIKOT_ANALYTICS = ":trikot-analytics:analytics"
    const val TRIKOT_VIEWMODELS = ":trikot-viewmodels:viewmodels"
    const val TRIKOT_VIEWMODELS_SAMPLE_COMMON = ":trikot-viewmodels:sample:common"
    const val TRIKOT_VIEWMODELS_DECLARATIVE = ":trikot-viewmodels-declarative:viewmodels-declarative"
    const val TRIKOT_VIEWMODELS_DECLARATIVE_COMPOSE = ":trikot-viewmodels-declarative:compose"
    const val TRIKOT_VIEWMODELS_DECLARATIVE_SAMPLE_COMMON = ":trikot-viewmodels-declarative:sample:common"
    const val TRIKOT_DATASOURCES = ":trikot-datasources:datasources"
}
