name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release library
    # simulator names changed in macos-12 . Waiting on this to be released
    # https://github.com/JetBrains/kotlin/commit/10947e2c45255cf89b8cee1598017b6fc61b0079
    runs-on: macos-11
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Gradle Cache
        uses: actions/cache@v3
        with:
          key: gradle-${{ hashFiles('**/gradle.properties') }}
          restore-keys: gradle-
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper

      - name: Kotlin Native Cache
        uses: actions/cache@v3
        with:
          key: kotlin-native-${{ hashFiles('gradle.properties') }}
          path: ~/.konan

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Release with gradle
        env:
          MAVEN_AWS_KEY: ${{ secrets.MIREGO_MAVEN_AWS_ACCESS_KEY_ID }}
          MAVEN_AWS_SECRET: ${{ secrets.MIREGO_MAVEN_AWS_SECRET_ACCESS_KEY }}
        run: |
          ./gradlew check publish -i -s
          ./gradlew tagVersion -i -s
